services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DEV_STORAGE_PRIVATE_PATH: /app/storage/private
    volumes:
      - ./storage/private:/app/storage/private
