spring.application.name=qltv
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.config.import=optional:file:.env[.properties]

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

app.storage.private-path=storage/private
