spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}
spring.datasource.driver-class-name=${PROD_DB_DRIVER}

jwt.secret=${PROD_JWT_SECRET}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.springframework.security=INFO

cloudinary.cloud-name=${PROD_CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${PROD_CLOUDINARY_API_KEY}
cloudinary.api-secret=${PROD_CLOUDINARY_API_SECRET}

app.storage.private-path=${PROD_STORAGE_PRIVATE_PATH:storage/private}
